name: deploy-staging

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      debug-container-node: ${{steps.filter.outputs.debug-container-node}}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            debug-container-node:
              - 'debug-container-node/**/*'

  debug-container-node:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{needs.changes.outputs.debug-container-node=='true'}}
    steps:
      - uses: action/checkout@v2
        with:
          ref: main
      - name: Get Commit SHA
        id: vars
        shell: bash
        run: |
          echo "Setting SHA"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Publish To Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/debug-container-node
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: debug-container-node/
      # - name: deploy to cluster
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     command: set image --record deployment/debug-container-node debug-container-node=tattletech/debug-container-node:${{ steps.vars.outputs.sha_short }}
      # - name: verify deployment
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     command: rollout status deployment/debug-container-node
